### ISSUE TITLE
Fehlermeldung bei ... ?

### ISSUE THREAD

**Issue by DavidPasch** [Bart1909/ioBroker.netatmo-crawler#5]
Ich bins seit Version 1.x am Testen - geiler Adapter übrigens. Schön das meine FB Frage nach einer Wetterstation und Feedback mit einem Script eine solche Entwicklung nimmt! :-)

Habe in Version 1.x und gestern auch 2.x täglich Nachts zwischen 0:00 und ca. 1:00 Uhr immer folgende Fehlermeldung:

netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
-- | -- | -- | --
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at endReadableNT (_stream_readable.js:1221:12)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at IncomingMessage.emit (events.js:327:22)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at Object.onceWrapper (events.js:421:28)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at Request.emit (events.js:315:20)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at Request.emit (events.js:315:20)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.netatmo-crawler/main.js:303:56)
netatmo-crawler.0 | 2020-07-03 00:45:12.018 | error | (27480) TypeError: Cannot read property 'value' of undefined
netatmo-crawler.0 | 2020-07-03 00:45:12.017 | error | (27480) unhandled promise rejection: Cannot read property 'value' of undefined
Unhandled | 2020-07-03 00:45:12.016 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

Ab ca. 1:00 läuft wieder alles, soweit kein Problem. Bin immer nur über den LOG erschrocken.
Ggf. Try/Catch mit Info-Meldungen aufbohren?

**Comment by DavidPasch** [comment]
Hat sich erledigt, gleicher "Bug" wie schon gemeldet. Nur eben nicht immer, sondern sporadisch bzw. nem bestimmten Zeitraum.
